function [im]=facet_isdwt21(SPsitLx,param)
% sdwt2
% inverse operator (for a single facet) (inverse = adjoint for spd, properly...
%implement the adjoint operator for different boundary conditions) u{q}

Q = length(param);
N =param(1).N;
spmd
    if labindex <=Q
        facet = isdwt21_sara(SPsitLx, ...
            param(labindex).I,....
            param(labindex).dims,...
            param(labindex).I_overlap_nc, ...
            param(labindex).dims_overlap_nc, ...
            param(labindex).Ncoefs,...
            param(labindex).N,...
            param(labindex).nlevel, ...
            param(labindex).wavelet,...
            param(labindex).dims_overlap,...
            param(labindex).I_overlap);
    else
        facet = sparse(N(1),N(2));
    end
    labBarrier;
    im = gplus(facet,Q);
end



